title: Adriana Homolová # your name (or website title) here
logo: "/avatar.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Freelance Data journalist  
  <br><br>
  Python charmer, public spending nerd, otaku, amateur shirmp keeper
  <br><br>
  <a href="https://www.linkedin.com/in/ahomolova/">LinkedIn</a>
  <br><br>
  <a href="https://twitter.com/naberacka">Twitter</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
